# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: pinecone

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/pinecone
    binary: pinecone
    ldflags:
      - -X github.com/pinecone-io/cli/internal/build.Date={{.Date}}
      - -X github.com/pinecone-io/cli/internal/build.Commit={{.Commit}}
      - -X github.com/pinecone-io/cli/internal/build.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin

universal_binaries:
- replace: true

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

report_sizes: true

env_files:
  github_token: .env

blobs:
  - provider: gs
    bucket: pinecone-cli
    directory: "{{.Version}}"
  - provider: gs
    bucket: pinecone-cli
    directory: latest

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: pinecone-io
    name: cli

brews:
  - name: pinecone
    homepage: "https://www.pinecone.io"
    description: "Pinecone CLI"
    repository:
      owner: pinecone-io
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_GITHUB_API_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    skip_upload: auto
    directory: Formula
    license: "Apache-2.0"
    test: |
      system "#{bin} --help"
