name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive # Required for BATS submodules

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Build with GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: "~> v2"
          args: build --single-target --snapshot --clean

      - name: Install test dependencies
        run: |
          cd test
          chmod +x install-deps.sh
          ./install-deps.sh

      - name: Run tests
        env:
          SKIP_PCDEV_BUILD: "true"
        run: |
          ./pcdev config set-api-key $CLI_TEST_API_KEY
          cd test
          ./bats -r -p -j 5 tests/
