name: Goreleaser Publish

on:
  push:
    tags:
      - 'v*'

jobs:
    publish:
      runs-on: ubuntu-latest
      outputs:
        version: ${{ steps.prepare-version.outputs.version }}
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Set up Go
          uses: actions/setup-go@v2
        - name: Setup Google service account creds
          id: setup-google
          run: |
            echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDS_JSON_BASE64 }}" | base64 -d > /tmp/gcp_key.json
        - name: Run GoReleaser
          id: goreleaser
          uses: goreleaser/goreleaser-action@v6
          with:
            version: '~> v2'
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GOOGLE_APPLICATION_CREDENTIALS: "/tmp/gcp_key.json"
            HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
        
        - name: Prepare version
          id: prepare-version
          run: |
            version=echo "${{ steps.goreleaser.outputs.metadata }}" | jq -r ".tag" | cut -c 2-
            echo "Version is $version"
            echo version=$version >> $GITHUB_OUTPUT
    
    update-dev-formula:
      uses: pinecone-io/homebrew-tap/.github/workflows/update-dev-formula.yaml@main
      needs: publish
      with:
        version: ${{ needs.publish.outputs.version }}