name: Goreleaser Publish

on:
  push:
    tags:
      - 'v*'

jobs:
    publish:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: Set up Go
          uses: actions/setup-go@v2
        - name: Setup Google service account creds
          id: setup-google
          run: |
            echo "${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDS_JSON_BASE64 }}" | base64 -d > /tmp/gcp_key.json
        - name: Run GoReleaser
          uses: goreleaser/goreleaser-action@v6
          with:
            version: '~> v2'
            args: release --clean
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GOOGLE_APPLICATION_CREDENTIALS: "/tmp/gcp_key.json"
            HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}